Add support for Akeyless
DataDog/datadog-secret-backend pull request #14
Opened 2024-03-08 14:23 UTC by a-rhodes

2024-03-13 02:23 UTC, rapdev-sid commented
Added new backend provider - [Akeyless](https://docs.akeyless.io/docs/akeyless-overview). 

For testing this, you can run the following command to retrieve secrets:

`cat sample.json | go run main.go -config datadog-secret-backend.yaml`

Contents for sample.json below:

`{"version": "1.0", "secrets": ["akeyless:/secret-folder/datadog-sample-key"]}`

Reach out to me for datadog-secret-backend.yaml with akeyless creds and sample secret stored

2024-03-19 19:15 UTC, restump requested changes
Looks good. Let's add a CHANGELOG entry for the new version with akeyless support and keep the copyright on the command version at 2021.

2024-03-19 19:15 UTC, restump commented on main.go
> +	fmt.Fprintf(os.Stdout, "%s: v%s\n\nRapDev (https://www.rapdev.io) (c) 2024\n",
Let's leave the copyright at 2021 since that was when the tool was created.

2024-03-22 13:02 UTC, restump approved these changes

2024-03-22 14:07 UTC, merged